FROM bellsoft/alpaquita-linux-base:stream-musl
MAINTAINER Adrian Dvergsdal [atmoz.net]

# Steps done in one RUN layer:
# - Install upgrades and new packages
# - OpenSSH needs /var/run/sshd to run
# - Remove generic host keys, entrypoint generates unique keys
RUN apk update && apk add --no-cache bash shadow openssh-server-pam openssh-sftp-server
RUN ln -s /usr/sbin/sshd.pam /usr/sbin/sshd && mkdir -p /var/run/sshd && rm -f /etc/ssh/ssh_host_*key*

COPY files/sshd_config /etc/ssh/sshd_config
COPY files/create-sftp-user /usr/local/bin/
COPY files/entrypoint /

EXPOSE 22

ENTRYPOINT ["/entrypoint"]
